# Site settings
title: jsfest.berlin â€“ Berlin, September 2014
description: "jsfest.berlin is a collection of fine events around the web, happening in Berlin in September 2014"
baseurl: ""
url: "http://jsfest.berlin"

# Build settings
markdown: kramdown
permalink: pretty
